[tool.pylint.messages_control]
disable = [
    "invalid-name",
    "line-too-long",
    "redundant-u-string-prefix",
    "import-error",
    "anomalous-backslash-in-string",
    "wrong-import-position",
    "redefined-outer-name",
    "not-context-manager",
    "too-many-locals",
    "unnecessary-lambda",
    "consider-using-f-string",
    "duplicate-code"
]

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
