apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: db.:5432
    database: evidently
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      sslmode: 'disable'
